env:
    browser: true
    es6: true
extends: 
    - 'airbnb-base'
    - "eslint:recommended"
    - "plugin:react/recommended"
  
parser: babel-eslint

parserOptions:
    ecmaFeatures:
        experimentalObjectRestSpread: true
        jsx: true
    sourceType: module
plugins:
    - react
rules:
    indent:
        - error
        - 4
    linebreak-style:
            - error
            - unix
    quotes:
            - error
            - single
    semi:
            - error
            - always
