language: "python"

dist: trusty

python:
  - "3.5"
  - "3.6"

install:
  - "pip install -r requirements/src/tools.txt"
  - "pip-sync requirements/requirements-dev.txt"

script: "tox -e python$TRAVIS_PYTHON_VERSION"

notifications:
  email:
    - "commande.romain+papaye@gmail.com"
