language: "python"

python:
  - "3.5"
  - "3.6"

install:
  - "pip install -r requirements/tools.txt"
  - "pip-sync requirements/requirements-dev.txt"

script: "tox"

notifications:
  email:
    - "commande.romain+papaye@gmail.com"
