language: python
dist: trusty
sudo: required
services:
- docker
python:
- '3.5'
- '3.6'
install:
- pip install -r requirements/src/ci.in
script: ./travis.sh $SONAR_TOKEN $GITHUB_TOKEN $TRAVIS_PULL_REQUEST $TRAVIS_JOB_NUMBER
notifications:
  email:
  - commande.romain+papaye@gmail.com
env:
  global:
  - secure: D01F55npuCVyIAI4/y4ChpDbdH4SEMxgu7abMPFfFaF/qfXO67qFQgDwsixjvawJIfT2v/ArMu8OTxl3uE+5bQdSOt7NQb58q2aP4al+wlXCokoOs10payhn3TNDpPPR1gMl5l2mThjVODpLq7obQGPjFizmj6Bs/0YYFvnDLK8=
  - secure: WiiAV0nNr9klADYypum2WgavX0oYk1x30KXUA3pFlvAEejUserWlpm3U6ix/z4GeAmavQavbcY1ZdYmWq+lJc4nFOk0RoIcUBVX+HenYsvXK3a3DcdO6pUtFs27sy5RCRlODXMD305EzgAngf3T6EetyrDO/KJlXBZReKa4PmlE=
