language: python
dist: trusty
sudo: required
services:
- docker
python:
- '3.5'
- '3.6'
install:
- pip install -r requirements/src/ci.in
script: "./travis.sh"
notifications:
  email:
  - commande.romain+papaye@gmail.com
env:
  global:
  - secure: YGf1+n3kMLlBSCF6n43blJFDkqE61nvf/ucH56e4PGPebf9NmgzQgSmkEzmNWDL5AU0S5VKLJJIHZNHf1+P89MBaO+plFgaTZS8+g1bTuOfqXmkwa+PJT+LlP9kDWRz9Mi+yiejxFHRbmm/iUjSifBkzoYSRngrxpks2ftO9IrQ=
  - secure: Abnyn5rLr5nSKyrAHRUhIuwfUnBB/xUayf1pbKWBgRV89xQtUXLYevAjcX9M01FelSHEaBJKSsEPeTIoKnh4lBEecB8850Y0zTwgvPcAW5LrxwmQjdvvgPEnA9Yyfgf4Duuplorm+aKb7cTi8PK1VjFN2y6Z0L3HCeKN8OCNRq4=
