# Wire up travis
language: "python"

python:
  - "3.3"
  - "3.4"

install:
  - "pip install ."
  - "pip install -r requirements_develop.txt"

script: "nose2"

notifications:
  email:
    - "commande.romain@gmail.com"
