language: "python"

dist: trusty

sudo: required

services:
  - docker

env:
  secure: "LYqcvGSdvfhmE7zjUV3uimYkK2CiBLCmKlY48DClyHPNHSQal/Tgu6jdEjHlHk7nelBgQNTl43FzojCkMl3I1q2tI/jpSOXvapuI4Elc1ps3Bo/oVczCoRHirxBcnmusHQQHKTOixMDO12eLKrYNoVOZ4x5bl+98Bpat81Vw4Oo="

python:
  - "3.5"
  - "3.6"

install:
  - "pip install -r requirements/src/tools.in"
  #- "pip-sync requirements/requirements-dev.txt"

script: 
  - tox -e python$TRAVIS_PYTHON_VERSION
  - coverage xml -i || true
  - sed -i 's/filename="/filename=".\//g' coverage.xml || true
  - docker run -v `pwd`:/data rcommande/sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=rcommande -Dsonar.sources=/data/. -Dsonar.projectKey=papaye

notifications:
  email:
    - "commande.romain+papaye@gmail.com"
