FROM ubuntu:16.04

MAINTAINER Romain Commandé, commande.romain@gmail.com

#VOLUME /packages

RUN apt-get update
RUN apt-get install -y python-pip python-virtualenv build-essential python3-dev libzmq-dev libxml2-dev libxslt1-dev zlib1g-dev docker.io
#RUN virtualenv -p /usr/bin/python3 /srv/papaye-venv
#RUN /srv/papaye-venv/bin/pip install wheel
#RUN /srv/papaye-venv/bin/pip wheel -w /packages uwsgi gunicorn
#RUN mkdir /srv/papaye
#COPY . /srv/papaye
#WORKDIR /srv/papaye/
#RUN /srv/papaye-venv/bin/pip install -U pip
#COPY dev.txt /requirements.txt
COPY requirements/dev.txt requirements_dev.txt
RUN pip install -r requirements_dev.txt
COPY . /papaye
WORKDIR /papaye
#RUN /srv/papaye-venv/bin/pip install .
#RUN /srv/papaye-venv/bin/pip wheel -r requirements/dev.txt -w /packages
#RUN /srv/papaye-venv/bin/pip install -r /srv/papaye/requirements.txt
#CMD /srv/papaye-venv/bin/papaye_init --user admin --password admin /srv/papaye/docker.ini && /srv/papaye-venv/bin/papaye_evolve /srv/papaye/docker.ini && /srv/papaye-venv/bin/uwsgi --http=0.0.0.0:8080 --paste config:/srv/papaye/docker.ini --enable-threads
